## Data Cleaning

In [61]:
import pandas as pd

import numpy as np

In [62]:
data = pd.read_csv(r"C:\Users\USER\Downloads\Datasets(Techcrush)\Datasets\dirty_cafe_sales.csv")

In [63]:
data

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [64]:
data.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [65]:
data.shape

(10000, 8)

In [66]:
data.head(10)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
5,TXN_2602893,Smoothie,5,4.0,20.0,Credit Card,NaN,2023-03-31
6,TXN_4433211,UNKNOWN,3,3.0,9.0,ERROR,Takeaway,2023-10-06
7,TXN_6699534,Sandwich,4,4.0,16.0,Cash,UNKNOWN,2023-10-28
8,TXN_4717867,NaN,5,3.0,15.0,NaN,Takeaway,2023-07-28
9,TXN_2064365,Sandwich,5,4.0,20.0,NaN,In-store,2023-12-31

In [67]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9667 non-null   object
 2   Quantity          9862 non-null   object
 3   Price Per Unit    9821 non-null   object
 4   Total Spent       9827 non-null   object
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: object(8)
memory usage: 625.1+ KB

In [68]:
#Checking for null values

data.isna().sum()

Transaction ID         0
Item                 333
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64

In [69]:
#When you are dealing with date, it should be stored in date_time format

#Lets check wahts in the transaction date first

data["Transaction Date"].value_counts()

Transaction Date
UNKNOWN       159
ERROR         142
2023-06-16     40
2023-02-06     40
2023-09-21     39
             ...
2023-11-24     15
2023-07-30     15
2023-07-22     14
2023-03-11     14
2023-02-17     14
Name: count, Length: 367, dtype: int64

In [70]:
#We need to drop the unknown and error because we need actual dates and we cant manufacture dates

data["Transaction Date"] = data["Transaction Date"].replace(["UNKNOWN", "ERROR"],pd.NA)

In [71]:
data.isna().sum()
#You can see that the transaction date is now 460 from 159 because we have converted the unknown and error values to nullvalues

Transaction ID         0
Item                 333
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     460
dtype: int64

In [72]:
#This is how to drop null values

data.dropna(subset = ["Transaction Date"], inplace = True)

In [73]:
data.isna().sum()

Transaction ID         0
Item                 315
Quantity             135
Price Per Unit       165
Total Spent          157
Payment Method      2439
Location            3118
Transaction Date       0
dtype: int64

In [74]:
data.shape

(9540, 8)

In [75]:
#Converting the transaction date to date-time data type for easy working usign python

data["Transaction Date"] = pd.to_datetime(data["Transaction Date"])

In [76]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9540 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    9540 non-null   object
 1   Item              9225 non-null   object
 2   Quantity          9405 non-null   object
 3   Price Per Unit    9375 non-null   object
 4   Total Spent       9383 non-null   object
 5   Payment Method    7101 non-null   object
 6   Location          6422 non-null   object
 7   Transaction Date  9540 non-null   datetime64[ns]
dtypes: datetime64[ns](1), object(7)
memory usage: 670.8+ KB

In [77]:
data.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [78]:
data["Item"].value_counts()

Item
Juice       1124
Coffee      1123
Salad       1099
Cake        1082
Sandwich    1075
Smoothie    1048
Cookie      1035
Tea         1027
UNKNOWN      329
ERROR        283
Name: count, dtype: int64

In [79]:
data["Item"] = data["Item"].replace({"ERROR":"UNKNOWN"})

In [80]:
data["Item"].value_counts()

Item
Juice       1124
Coffee      1123
Salad       1099
Cake        1082
Sandwich    1075
Smoothie    1048
Cookie      1035
Tea         1027
UNKNOWN      612
Name: count, dtype: int64

In [81]:
data.isna().sum()

Transaction ID         0
Item                 315
Quantity             135
Price Per Unit       165
Total Spent          157
Payment Method      2439
Location            3118
Transaction Date       0
dtype: int64

In [82]:
#To fill your null values to no longer be empty values

data["Item"] = data["Item"].fillna("UNKNOWN")

In [83]:
data["Item"].value_counts()

Item
Juice       1124
Coffee      1123
Salad       1099
Cake        1082
Sandwich    1075
Smoothie    1048
Cookie      1035
Tea         1027
UNKNOWN      927
Name: count, dtype: int64

In [84]:
data.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [85]:
data["Location"].value_counts()

Location
Takeaway    2889
In-store    2872
ERROR        341
UNKNOWN      320
Name: count, dtype: int64

In [86]:
#We are replacing error with unknown too here

data["Location"] = data["Location"].replace({"ERROR":"UNKNOWN"})

In [87]:
data["Location"] = data["Location"].fillna("UNKNOWN")

In [88]:
data.isna().sum()

Transaction ID         0
Item                   0
Quantity             135
Price Per Unit       165
Total Spent          157
Payment Method      2439
Location               0
Transaction Date       0
dtype: int64

In [89]:
data["Payment Method"].value_counts()

Payment Method
Digital Wallet    2197
Credit Card       2170
Cash              2158
ERROR              296
UNKNOWN            280
Name: count, dtype: int64

In [90]:
data["Payment Method"] = data["Payment Method"].replace({"ERROR":"UNKNOWN"})

In [91]:
data["Payment Method"] = data["Payment Method"].fillna("UNKNOWN")

In [92]:
data.isna().sum()

Transaction ID        0
Item                  0
Quantity            135
Price Per Unit      165
Total Spent         157
Payment Method        0
Location              0
Transaction Date      0
dtype: int64

In [93]:
#To convert/to ensure the three numerical column are all numbers

data["Quantity"].value_counts()

Quantity
5          1914
2          1892
4          1774
3          1766
1          1740
UNKNOWN     160
ERROR       159
Name: count, dtype: int64

In [94]:
data["Quantity"] = data["Quantity"].replace({"UNKNOWN":0, "ERROR":0})

In [95]:
data["Quantity"].value_counts()

Quantity
5    1914
2    1892
4    1774
3    1766
1    1740
0     319
Name: count, dtype: int64

In [96]:
data["Price Per Unit"].value_counts()

Price Per Unit
3.0        2319
4.0        2219
2.0        1185
5.0        1150
1.0        1088
1.5        1073
ERROR       186
UNKNOWN     155
Name: count, dtype: int64

In [97]:
data["Price Per Unit"] = data["Price Per Unit"].replace({"UNKNOWN":0, "ERROR":0})

In [98]:
data.isna().sum()

Transaction ID        0
Item                  0
Quantity            135
Price Per Unit      165
Total Spent         157
Payment Method        0
Location              0
Transaction Date      0
dtype: int64

In [99]:
#Turning the parameters that must be in numerical values into numerical values

data["Quantity"] = pd.to_numeric(data["Quantity"], errors = "coerce")

data["Price Per Unit"] = pd.to_numeric(data["Price Per Unit"], errors = "coerce")

In [100]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9540 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    9540 non-null   object
 1   Item              9540 non-null   object
 2   Quantity          9405 non-null   float64
 3   Price Per Unit    9375 non-null   float64
 4   Total Spent       9383 non-null   object
 5   Payment Method    9540 non-null   object
 6   Location          9540 non-null   object
 7   Transaction Date  9540 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(2), object(5)
memory usage: 670.8+ KB

In [101]:
data.isna().sum()

Transaction ID        0
Item                  0
Quantity            135
Price Per Unit      165
Total Spent         157
Payment Method        0
Location              0
Transaction Date      0
dtype: int64

In [102]:
#Fill with mean when your data is free of outliers while you fill with median when your data is not free of outliers

data["Quantity"] = data["Quantity"].fillna(data ["Quantity"].mean())

data["Price Per Unit"] = data["Price Per Unit"].fillna(data ["Price Per Unit"].mean())

In [103]:
data.isna().sum()

Transaction ID        0
Item                  0
Quantity              0
Price Per Unit        0
Total Spent         157
Payment Method        0
Location              0
Transaction Date      0
dtype: int64

In [104]:
data.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4.0,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2.0,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [105]:
#Sometimes is best to create your own column of total spent

data["Total Spent"] = data["Quantity"] * data["Price Per Unit"]

In [106]:
data.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4.0,1.0,4.0,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2.0,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [107]:
data.sample(6)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
2425,TXN_6476304,Sandwich,2.0,4.0,8.0,Credit Card,UNKNOWN,2023-03-17
6435,TXN_4296023,Tea,5.0,1.5,7.5,Digital Wallet,In-store,2023-10-08
583,TXN_7596587,Tea,3.0,1.5,4.5,Credit Card,UNKNOWN,2023-02-08
1294,TXN_9971927,Smoothie,3.0,4.0,12.0,UNKNOWN,Takeaway,2023-08-07
6702,TXN_8903514,Salad,4.0,5.0,20.0,UNKNOWN,Takeaway,2023-09-14
5759,TXN_4986668,Cake,3.0,3.0,9.0,Digital Wallet,UNKNOWN,2023-11-30

In [108]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9540 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    9540 non-null   object
 1   Item              9540 non-null   object
 2   Quantity          9540 non-null   float64
 3   Price Per Unit    9540 non-null   float64
 4   Total Spent       9540 non-null   float64
 5   Payment Method    9540 non-null   object
 6   Location          9540 non-null   object
 7   Transaction Date  9540 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(3), object(4)
memory usage: 670.8+ KB

In [109]:
data.isna().sum()

Transaction ID      0
Item                0
Quantity            0
Price Per Unit      0
Total Spent         0
Payment Method      0
Location            0
Transaction Date    0
dtype: int64

In [110]:
#To check for duplicates in the data

data.duplicated().sum()

np.int64(0)

In [111]:
#Lets say you want to extract the month from your date to a new column

data["Month"] = data["Transaction Date"].dt.month

In [112]:
data.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date,Month
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08,9
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store,2023-05-16,5
2,TXN_4271903,Cookie,4.0,1.0,4.0,Credit Card,In-store,2023-07-19,7
3,TXN_7034554,Salad,2.0,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27,4
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11,6

In [113]:
data["Month_in_words"] = data["Transaction Date"].dt.month_name()

In [114]:
data.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date,Month,Month_in_words
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08,9,September
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store,2023-05-16,5,May
2,TXN_4271903,Cookie,4.0,1.0,4.0,Credit Card,In-store,2023-07-19,7,July
3,TXN_7034554,Salad,2.0,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27,4,April
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11,6,June

In [115]:
data["Day_in_words"] = data["Transaction Date"].dt.day_name()

In [116]:
data.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date,Month,Month_in_words,Day_in_words
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08,9,September,Friday
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store,2023-05-16,5,May,Tuesday
2,TXN_4271903,Cookie,4.0,1.0,4.0,Credit Card,In-store,2023-07-19,7,July,Wednesday
3,TXN_7034554,Salad,2.0,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27,4,April,Thursday
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11,6,June,Sunday

In [117]:
#To save your data into a new CSV file

data.to_csv("Cleaned_cafe-sales.csv", index = False)

In [118]:
#If you import a data and you dont want nto modify the original data, you can work on the copied version the same way we copy other data