## Joining Datasets in Pandas

In [1]:
import pandas as pd

import numpy as np

## Using Concat

In [6]:
df1 = pd.DataFrame({"A":[1,2], "B":[3,4]})

df1

   A  B
0  1  3
1  2  4

In [7]:
df2 = pd.DataFrame({"C":[5,6], "D":[7,8]})

df2

   C  D
0  5  7
1  6  8

In [8]:
#To concatenate both frames now

df3 = pd.concat([df1,df2], axis = 1) #The axis= 1 will concatenate column_wise

df3

   A  B  C  D
0  1  3  5  7
1  2  4  6  8

In [9]:
df4 = pd.concat([df1,df2], axis = 0) #To concatenate along rows

df4

     A    B    C    D
0  1.0  3.0  NaN  NaN
1  2.0  4.0  NaN  NaN
0  NaN  NaN  5.0  7.0
1  NaN  NaN  6.0  8.0

In [10]:
df4.isna().sum()

A    2
B    2
C    2
D    2
dtype: int64

In [11]:
df4.fillna(0, inplace = True)

In [12]:
df4

     A    B    C    D
0  1.0  3.0  0.0  0.0
1  2.0  4.0  0.0  0.0
0  0.0  0.0  5.0  7.0
1  0.0  0.0  6.0  8.0

## Using Merge(There are different types of join here)

In [13]:
df5 = pd.DataFrame({"ID":[1,2,3], "Name":["Alice", "Bob", "Charles"]})

df5

   ID     Name
0   1    Alice
1   2      Bob
2   3  Charles

In [14]:
df6 = pd.DataFrame({"ID":[2,3,4], "Score":[85, 90, 95]})

df6

   ID  Score
0   2     85
1   3     90
2   4     95

### Inner Join

**This returns records present in both tables based on the common column**

In [15]:
pd.merge(df5,df6, on = "ID", how = "inner")

   ID     Name  Score
0   2      Bob     85
1   3  Charles     90

### The Left Join

**This returns all the records present in the left table and record present in both tables**

In [17]:
pd.merge(df5,df6, on = "ID", how = "left")#Remember the left table is the table you first specify in your arguement

   ID     Name  Score
0   1    Alice    NaN
1   2      Bob   85.0
2   3  Charles   90.0

## The Right Join

**This returns all the records present in the right table and records present in both tables**

In [18]:
pd.merge(df5,df6, on = "ID", how = "right")

   ID     Name  Score
0   2      Bob     85
1   3  Charles     90
2   4      NaN     95

In [19]:
df7 = pd.DataFrame({"Student_ID":[2,3,4], "Score":[85, 90, 95]})

df7

   Student_ID  Score
0           2     85
1           3     90
2           4     95

In [22]:
#for instance if the column are named differently in the data frame and you don't want to rename and that's the common column you want to join on

df8 = pd.merge(df5, df7, left_on = "ID", right_on = "Student_ID", how = "inner")

df8

   ID     Name  Student_ID  Score
0   2      Bob           2     85
1   3  Charles           3     90

In [23]:
df8.drop("Student_ID", axis = 1, inplace = True)

In [24]:
df8

   ID     Name  Score
0   2      Bob     85
1   3  Charles     90

## Outer Join

**This returns all colums(all records)**

In [25]:
pd.merge(df5,df6, on = "ID", how = "outer")

   ID     Name  Score
0   1    Alice    NaN
1   2      Bob   85.0
2   3  Charles   90.0
3   4      NaN   95.0

## Joining on Index

**We mainly use this when we are working on time series data**

In [26]:
df5

   ID     Name
0   1    Alice
1   2      Bob
2   3  Charles

In [27]:
df6

   ID  Score
0   2     85
1   3     90
2   4     95

In [28]:
#To set the index to ID

df5.set_index("ID",inplace = True)

df6.set_index("ID", inplace = True)

In [29]:
df5

       Name
ID
1     Alice
2       Bob
3   Charles

In [30]:
df6

    Score
ID
2      85
3      90
4      95

In [31]:
df5.index

Index([1, 2, 3], dtype='int64', name='ID')

In [32]:
df6.index

Index([2, 3, 4], dtype='int64', name='ID')

In [34]:
#You use this because you are joining on the index

pd.merge(df5, df6, left_index = True, right_index = True, how = "inner")

       Name  Score
ID
2       Bob     85
3   Charles     90

## Using Join

**For you to use join, it has to be an index or you set it to index, it must join on the index**

In [38]:
df5.join(df6)

       Name  Score
ID
1     Alice    NaN
2       Bob   85.0
3   Charles   90.0

In [39]:
df6.join(df5)

    Score     Name
ID
2      85      Bob
3      90  Charles
4      95      NaN