In [48]:
import pandas as pd

## Pandas Series

In [49]:
data = pd.Series([1.4, 3, 5, 6])

data

0    1.4
1    3.0
2    5.0
3    6.0
dtype: float64

In [50]:
type(data)

pandas.core.series.Series

In [51]:
#Lets assume you want to use your own indexing

data_explicit =  pd.Series([1.4, 3, 5, 6], index = ["a", "b", "c", "d"])

data_explicit

a    1.4
b    3.0
c    5.0
d    6.0
dtype: float64

In [52]:
data.index #Always remember that attributes do not carry parenthesis() at the end of the instruction

RangeIndex(start=0, stop=4, step=1)

In [53]:
#Anything string or quotation is reped aas object in pandas

data_explicit.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [54]:
data_explicit.values

array([1.4, 3. , 5. , 6. ])

In [55]:
data_explicit["b"]

np.float64(3.0)

In [56]:
data_explicit[3]

C:\Users\USER\AppData\Local\Temp\ipykernel_1740\4115700679.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  data_explicit[3]

np.float64(6.0)

In [57]:
data_explicit

a    1.4
b    3.0
c    5.0
d    6.0
dtype: float64

In [58]:
data_explicit[:3]

a    1.4
b    3.0
c    5.0
dtype: float64

In [59]:
data_explicit[:4]

a    1.4
b    3.0
c    5.0
d    6.0
dtype: float64

## Pandas Dataframe

#### Here Dictionary is the foundation of a dataframe

In [60]:
heights = {"John": 1.70, "Alice": 1.65, "Fred": 1.78, "Jane": 1.50}

weights = {"John": 60, "Alice": 50, "Fred": 70, "Jane": 55}

In [61]:
#Don't use "print" to print your DataFrame because it doesn't format it properly the way you want it

bmi_info = pd.DataFrame({"height": heights, "weight": weights})

bmi_info

       height  weight
John     1.70      60
Alice    1.65      50
Fred     1.78      70
Jane     1.50      55

In [62]:
type(bmi_info)

pandas.core.frame.DataFrame

In [63]:
#Anothe way to create a DataFrame

data = {"Name": ["John", "Alice", "Fred", "Jane"], "Height": [1.70, 1.65, 1.78, 1.50], "Weight": [60, 50, 70, 55]}

In [64]:
df = pd.DataFrame(data)

In [65]:
df

    Name  Height  Weight
0   John    1.70      60
1  Alice    1.65      50
2   Fred    1.78      70
3   Jane    1.50      55

In [66]:
bmi_info

       height  weight
John     1.70      60
Alice    1.65      50
Fred     1.78      70
Jane     1.50      55

In [67]:
bmi_info.index

Index(['John', 'Alice', 'Fred', 'Jane'], dtype='object')

In [68]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [69]:
#If you want to reset the index 

bmi_info.reset_index()

   index  height  weight
0   John    1.70      60
1  Alice    1.65      50
2   Fred    1.78      70
3   Jane    1.50      55

In [70]:
#To update the new index in your DataFrame, use inplace = True

bmi_info.reset_index(inplace = True)

In [71]:
bmi_info

   index  height  weight
0   John    1.70      60
1  Alice    1.65      50
2   Fred    1.78      70
3   Jane    1.50      55

In [72]:
#To rename a column *******

bmi_info.rename(columns={"index":"name"}, inplace=True)

In [73]:
bmi_info

    name  height  weight
0   John    1.70      60
1  Alice    1.65      50
2   Fred    1.78      70
3   Jane    1.50      55

In [74]:
Clean_bmi_info = bmi_info.drop(columns=["level_0"], errors="ignore").reset_index(drop=True)

In [75]:
Clean_bmi_info

    name  height  weight
0   John    1.70      60
1  Alice    1.65      50
2   Fred    1.78      70
3   Jane    1.50      55

In [76]:
#To acces the values in a column, just pass in the name of the column

Clean_bmi_info["name"]

0     John
1    Alice
2     Fred
3     Jane
Name: name, dtype: object

In [77]:
Clean_bmi_info["height"]

0    1.70
1    1.65
2    1.78
3    1.50
Name: height, dtype: float64

## Different ways to access data in a DataFrame

#### Using loc

In [78]:
Clean_bmi_info

    name  height  weight
0   John    1.70      60
1  Alice    1.65      50
2   Fred    1.78      70
3   Jane    1.50      55

In [79]:
#Loc uses the explicit index not the zeros and ones

Clean_bmi_info.set_index("name", inplace=True)

In [80]:
Clean_bmi_info

       height  weight
name
John     1.70      60
Alice    1.65      50
Fred     1.78      70
Jane     1.50      55

In [81]:
Clean_bmi_info.index

Index(['John', 'Alice', 'Fred', 'Jane'], dtype='object', name='name')

In [82]:
#Use loc to select an element from the DataFrame

Clean_bmi_info.loc["John", "height"]

np.float64(1.7)

In [83]:
Clean_bmi_info.loc["Fred", "weight"]

np.int64(70)

In [84]:
#Slicing

Clean_bmi_info.loc[:"Fred", :]

       height  weight
name
John     1.70      60
Alice    1.65      50
Fred     1.78      70

#### Using iloc

In [85]:
df

    Name  Height  Weight
0   John    1.70      60
1  Alice    1.65      50
2   Fred    1.78      70
3   Jane    1.50      55

In [86]:
#John's height is at index zero column 1

df.iloc[0,1]

np.float64(1.7)

In [87]:
df.iloc[3,2]

np.int64(55)

In [88]:
#More like indexing


df.iloc[:, :2]

    Name  Height
0   John    1.70
1  Alice    1.65
2   Fred    1.78
3   Jane    1.50

In [89]:
#More like indexing

df.iloc[:, :3]

    Name  Height  Weight
0   John    1.70      60
1  Alice    1.65      50
2   Fred    1.78      70
3   Jane    1.50      55

In [90]:
#Adding new colums to the DataFrame


df

    Name  Height  Weight
0   John    1.70      60
1  Alice    1.65      50
2   Fred    1.78      70
3   Jane    1.50      55

In [91]:
df["bmi"] = df["Weight"]/(df["Height"]**2)

In [92]:
df

    Name  Height  Weight        bmi
0   John    1.70      60  20.761246
1  Alice    1.65      50  18.365473
2   Fred    1.78      70  22.093170
3   Jane    1.50      55  24.444444

## Importing Data sets

In [95]:
#You can either add r to the beginnign of the pasted path for python to be able to read it

population_df = pd.read_csv(r"C:\Users\USER\Downloads\Datasets(Techcrush)\Datasets\world_population.csv")

In [94]:
population_df

,Rank,CCA3,Country/Territory,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
0,36,AFG,Afghanistan,Kabul,Asia,41128771,38972230,33753499,28189672,19542982,10694796,12486631,10752971,652230,63.0587,1.0257,0.52
1,138,ALB,Albania,Tirana,Europe,2842321,2866849,2882481,2913399,3182021,3295066,2941651,2324731,28748,98.8702,0.9957,0.04
2,34,DZA,Algeria,Algiers,Africa,44903225,43451666,39543154,35856344,30774621,25518074,18739378,13795915,2381741,18.8531,1.0164,0.56
3,213,ASM,American Samoa,Pago Pago,Oceania,44273,46189,51368,54849,58230,47818,32886,27075,199,222.4774,0.9831,0.00
4,203,AND,Andorra,Andorra la Vella,Europe,79824,77700,71746,71519,66097,53569,35611,19860,468,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,226,WLF,Wallis and Futuna,Mata-Utu,Oceania,11572,11655,12182,13142,14723,13454,11315,9377,142,81.4930,0.9953,0.00
230,172,ESH,Western Sahara,El Aaiún,Africa,575986,556048,491824,413296,270375,178529,116775,76371,266000,2.1654,1.0184,0.01
231,46,YEM,Yemen,Sanaa,Asia,33696614,32284046,28516545,24743946,18628700,13375121,9204938,6843607,527968,63.8232,1.0217,0.42
232,63,ZMB,Zambia,Lusaka,Africa,20017675,18927715,16248230,13792086,9891136,7686401,5720438,4281671,752612,26.5976,1.0280,0.25
233,74,ZWE,Zimbabwe,Harare,Africa,16320537,15669666,14154937,12839771,11834676,10113893,7049926,5202918,390757,41.7665,1.0204,0.20

In [96]:
# or you turn the slashes the other way

population_df = pd.read_csv("C:/Users/USER/Downloads/Datasets(Techcrush)/Datasets/world_population.csv")

In [97]:
population_df

,Rank,CCA3,Country/Territory,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
0,36,AFG,Afghanistan,Kabul,Asia,41128771,38972230,33753499,28189672,19542982,10694796,12486631,10752971,652230,63.0587,1.0257,0.52
1,138,ALB,Albania,Tirana,Europe,2842321,2866849,2882481,2913399,3182021,3295066,2941651,2324731,28748,98.8702,0.9957,0.04
2,34,DZA,Algeria,Algiers,Africa,44903225,43451666,39543154,35856344,30774621,25518074,18739378,13795915,2381741,18.8531,1.0164,0.56
3,213,ASM,American Samoa,Pago Pago,Oceania,44273,46189,51368,54849,58230,47818,32886,27075,199,222.4774,0.9831,0.00
4,203,AND,Andorra,Andorra la Vella,Europe,79824,77700,71746,71519,66097,53569,35611,19860,468,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,226,WLF,Wallis and Futuna,Mata-Utu,Oceania,11572,11655,12182,13142,14723,13454,11315,9377,142,81.4930,0.9953,0.00
230,172,ESH,Western Sahara,El Aaiún,Africa,575986,556048,491824,413296,270375,178529,116775,76371,266000,2.1654,1.0184,0.01
231,46,YEM,Yemen,Sanaa,Asia,33696614,32284046,28516545,24743946,18628700,13375121,9204938,6843607,527968,63.8232,1.0217,0.42
232,63,ZMB,Zambia,Lusaka,Africa,20017675,18927715,16248230,13792086,9891136,7686401,5720438,4281671,752612,26.5976,1.0280,0.25
233,74,ZWE,Zimbabwe,Harare,Africa,16320537,15669666,14154937,12839771,11834676,10113893,7049926,5202918,390757,41.7665,1.0204,0.20